server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dingcloud
    #    url: jdbc:postgresql://47.94.194.45:5432/dingcloud
    username: postgres
    password: postgres
str:
  all: 饺子,麻辣烫,臊子面